kind: Secret
apiVersion: v1
metadata:
    name: pelando-api-secrets
    namespace: production-apps
stringData:
    NODE_ENV: ENC[AES256_GCM,data:b9IxRBcaSLe8zA==,iv:tVsFkDn7np4MubGq74lO6eGUWgDTCdjPFfSQ8BVxETs=,tag:TgiYmhYG4szNPZlWpuhFGw==,type:str]
    NODE_PORT: ENC[AES256_GCM,data:q9cXEg==,iv:9iup3J5pIdlOsztEchEmui8/mhhrADfXJPRVopOCKWo=,tag:7rrWzKWJBl9aY0HiEBR+Nw==,type:str]
    NODE_HOST: ENC[AES256_GCM,data:czytAff+vQ==,iv:tDzGq6Ps/s3DU7a2NgsGO/OuLMmtINRsXBmf3hQ1kgE=,tag:yrnO1ZqwhyHxgh/X+HLewQ==,type:str]
    POSTGRES_CONNECTION_STRING: ENC[AES256_GCM,data:R8iBzmBZl6O+r53gk5oFiVAzNyI+lMLxuvGM2E/I3onobTkvdUBuOQ0H9uWhcCI7eWUaIfrthDrq7KjD5g==,iv:LBDJO1SOA6iDtxZG97mJWBJkKyB0PxA8IVwNAVJRyyY=,tag:pkpRQA8Fp5SqXCkz0o/Lqg==,type:str]
    REDIS_TTL: ENC[AES256_GCM,data:nJOIpg==,iv:KdkgJxgV0IkrTRvb9Xgfrzy6xVFdf5ZvGS2FkFp6mAw=,tag:9L+ervDb5KgCIrbEx18Djg==,type:str]
    REDIS_CONNECTION_STRING: ENC[AES256_GCM,data:/t9sLgs3RkalA2XUzfIgIXZ+Cv4s3kCRlFIrEPxyl38jYNAIdfg=,iv:/Xhg32Y3o/GKNX+DiJusU1aq+X2VE7DbazuyIDTjiYA=,tag:mdwkKj48srPZ9+QqXTJ52w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:Ine2xyyZ4Zdde876pJILmHFNTICDYgAggC47WeX6eSR5XKpm,iv:ePRz96Eb+phBs9wPF1tb2qJBiftUQHfaRS1ZnnY7C90=,tag:EqEnrvGN1k2MtrAaBbJd3w==,type:str]
    JWT_ALGORITHM: ENC[AES256_GCM,data:/jCAt1I=,iv:HS+nx+Y5iuVDq0wFEUmhLi4BfmOADPzJW8NGiREuDCM=,tag:0CkCZNvO3fEooF3eOIZZ8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5N0R4cnZlR0xFYkd1cU95
            V0VkeEFtRW5SOGdRbVdNNjloR3hiMmt3cEhJCnhZdnZxdTN0eUw5ZGh5bHBFTVZa
            UDc2S1FQSTJrODNNRW1KaTFRc1JCdnMKLS0tIDFOWnNud3dub0IrNTBwcHBxUVpQ
            WlJHWGE0UGw3djBNYVBzMm01UnRsM0UKNnxXd+w1c+kFayx3zlNe+af1yL+qs04V
            oRstYXjEzOo0hU4q28TKJQlKaKGoeYSm4q93/eBwR8+spOrw/E9/qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-06T23:40:32Z"
    mac: ENC[AES256_GCM,data:eIdWHPh5Lr1mlRX5bWJCI8r9XuAUrm+1iojbUk+Y1LmSE1oUBuwGlKF/m3ulp0UhpOaeWAf37BovsJsiai61Du+lV6keasfu7Bzv40qvHhx7qMe3UNqzecbxpuGofshm56Me8GWqLGrD7qjb+9K1m2ysfyR0aDVWhy6IlcgDOmM=,iv:HTxt5Yi64XZV8+J+DQb9U8XDe/mxGbk6Ddk0qW1a4ns=,tag:Dx278Uo4qtZqqatAtPVNNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
