kind: Secret
apiVersion: v1
metadata:
    name: pelando-api-secrets
    namespace: production-apps
stringData:
    APP_RELEASE: ENC[AES256_GCM,data:Unyhk1M=,iv:3lcVd3D68m3qDQ1iKPZwrZH9jA371GCaO9Cc+Cj1VEw=,tag:mAE+KeLHuzOtPzszWFdFqw==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:+GkMhAij1XYigg==,iv:CyhLKpurRyqGdq6a5ed7CPbBr39j/+tQxbuNGSixMvw=,tag:Wka0AoZNwIrN8JJOAddA2A==,type:str]
    FLASK_DEBUG: ENC[AES256_GCM,data:OhCMcLc=,iv:sBCqrqZ/4RdVH9iXWa6C0AhuMy8BZBpEsfoH796/Knk=,tag:YZDDU3BzpJ6JLBmMJL8r/w==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:n7k=,iv:Pr0EVFypUnWDqvcfcPokBRybyFZ/Sq30j+RiLRe98Ps=,tag:SyCM8V2M/sfbmGTz4T+k6w==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:QKxflhbd7w==,iv:onV9A0AQD5ObvVDHH8myNP6qcAwghsBaRrAiJsEHk/w=,tag:r4kTDqHcP4SvNrmHXEeO3Q==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:j67wlK8=,iv:0Otq06aMxxprRlDp61luCwcGbRYbYhNYfTD6Fu0yEbg=,tag:Rki5e9kOnFyn+5ScRC7RcQ==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:umOEF2oauwAJ/C/+zlNXm4H6+yImpACihg07/PrktP+ouLVzpLd7ZKkIecEIZO+oY5r5/g==,iv:XZNDe8KBuavxm4AYitIgqBjMWpz9mHW04mhOX2LNiLk=,tag:Xg+iGE17N51VDlEdaq+Gpg==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:VL3a+v8eVs4=,iv:hDqbX4wWpw+U126K6N6yAljzmZeG0jl3hfX5wHbWE+Y=,tag:CmmZgqysXURnLeBSVJ/0gw==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:ncnD3Q==,iv:UpoKC+uOqsoNwiOj6IA7jfrdvmvSs04vN2xt7c4zsP4=,tag:G8He8/nDQn4XQXZheEpLgQ==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:GO2Ejg==,iv:L8GWhGDVlNdVv914ikDUmsHo0qOAnpjmVRxAy4uXj/4=,tag:c07Pgp77B8WNpOzsztaw7w==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:x+xQXMb8lDlXOcaiTfDSRaKAo9PQrr/gTLJZHmOkYVYunFrj3/RVaX8lcsFudqBld8AtNTPzK2IIXOXG1aDarzj9hw==,iv:5zRthiUM09eRJAghHW0T0ebOD6Nwbdn6we42A1tgMqg=,tag:zWIpk4Uk4811DMjgHNEhVw==,type:str]
    X_API: ENC[AES256_GCM,data:Plz3AFjsUrZTyMVqICTtJVOPxPgbD5r37gfRKuzmkYNp5RA9ki6u1VpCuqn0ce4/aMrvlNan7WhaqQ==,iv:s2cOrbecD7sBhUbMLMdYeu1iLYSGqsj4tlbLsq9op6Y=,tag:rRjwArKnBdE86a2SCUVGnQ==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:jmebdcF8hT3fluJSr/9JHrtAAtY5FX8kMGlDd6X8RGWWPtE/I1j5vXaxhhIpMlrS1jfzRn2S/mGWM63heJyH2A==,iv:lp5PACOmgBFBBN8awRP3+BvM4Lcz2r17eXQk/zOXDgk=,tag:VDfpYsxnqaeiup8ymUogDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Q0NDVUt1N3dyQnQ2alZo
            L1ExSkE2b3Z5RERETUJHTDdWWnZINi9VSndJClVLejJmdHJwZVZWd3NLMy92clJh
            dmx3RXBxY1AyRFFqZjZ3WGJrT3dnSDQKLS0tIDFBZXJCUVcydGZzVjZudTdHY1Vo
            TDllREFDckg0ODl3U0ptSnhsSkd4ZWMKGtx1FBDK8WrkGfW0rNWlJ2EMZqbuL3eT
            eHgYAfRd3jsVycvXf5H8VbZKJmDvWArhBbqfB4tSNfxKmCMw2eIdKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T17:27:31Z"
    mac: ENC[AES256_GCM,data:6BUucMJJgUfDXazg21gowiKqu7F7SGH0bu9bXkuvAbmVZk6dF8rvB0O5ctMFjSlUbQ8Ce2rOQUHU/8/sTcbTYAPOwpY+Ep4YoecP/B6VY0pAma92kiiBtOcXE7kcxSgh+fbmiK9UlB/ZKcizYwUK5ILzhZYUqJDc/MIuPezhEH0=,iv:ul2tOYCj2iROjjik7qXpNpeZmzfdkgSBojBno3tB+p8=,tag:aQO/EX4lEKy7m/5i7+uQog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
