kind: Secret
apiVersion: v1
metadata:
    name: pelando-api-secrets
    namespace: staging-apps
stringData:
    APP_RELEASE: ENC[AES256_GCM,data:cYHYAvo=,iv:CR3MEqeVP5tcb2RbRwv05SFebgJcZTqRxyj6Fne8P+c=,tag:OlcQVwyrWgwzODsK41n0Dg==,type:str]
    APP_ENVIRONMENT: ENC[AES256_GCM,data:S7BD0tr+0w==,iv:JO7IMpYVtzRmh5y4Bha5O0eG5+GXvCrHri/sbagjvoE=,tag:cp7q+sAKN3Ofz9DIuzf/eA==,type:str]
    FLASK_DEBUG: ENC[AES256_GCM,data:8x5K+g==,iv:v2MKDwAqelGlYNU3hdyqa6fU3HJK1AHBAqfMX2XUzt4=,tag:/P4f6E6XeUvWnUJJ/i6gIQ==,type:str]
    FLASK_RUN_PORT: ENC[AES256_GCM,data:UWc=,iv:n/HkEcquIMoQWNwCztbbtrnqQIOY1DHkAzPaxesA3Ow=,tag:8qW4gk6L5drUtWHxxEUfYA==,type:str]
    FLASK_RUN_HOST: ENC[AES256_GCM,data:8uPRUzMHOA==,iv:n+ZAq9d40ejYhFbl9ULJNew0Xj0yhEKia6UFug8gpMM=,tag:T88+1d+LoE9ejdUJDHxXzA==,type:str]
    FLASK_DEBUGGER: ENC[AES256_GCM,data:wbTpiis=,iv:MgkCb2VxYO5TIFEkRhMx2rDT57Hwx3MUWU+so+dP5NU=,tag:s7lPg826AQYUpK9HodNAwA==,type:str]
    FLASK_DEBUGGER_PORT: ""
    MONGODB_URL: ENC[AES256_GCM,data:k75MuVxnuv3ecXOF/Wrfu2tQc1mD9a7ayMqEz5+RtDeVTKhbO8RpM0xlsWcX4dgqgNGK/Q==,iv:r1ZO8iWhB4jlApfLyGcS0ycpmby0Kkp7Mit18QajD58=,tag:Yz2cDmMNM3acTPuJDsai3w==,type:str]
    MONGODB_NAME: ENC[AES256_GCM,data:XCG56QF1Uy8=,iv:NWxW039JoUMQiVHSBLF2jCk+udqzuDo3ZaHVAKo7QDM=,tag:z6BZXXoRm+M7juSO9veMfw==,type:str]
    METRICS_USER: ENC[AES256_GCM,data:2vYIxw==,iv:oknSOchT+mfTquUpKJI/7pWsEwut2WDRqvyU6usPtkI=,tag:mRcBFqy7/uX3vobgxOwu8A==,type:str]
    METRICS_PASSWORD: ENC[AES256_GCM,data:pE3BWQ==,iv:/+6Gxnv90/OFN7J7XZ3v9J9N7yZDHG5LmtLXTjh0NuU=,tag:8xxC+CLsPOP/g5HBRgd9jw==,type:str]
    SENTRY_DSN: ENC[AES256_GCM,data:95wU+TYynCP7lKTugKCNojFgoWkLCpltJO6nZpBswiB8kqrbuPL9OPIkix+8zv7j/L0i5uUXICFE8LhQmIca37N0UA==,iv:aIauJ2GiJLg3r6+fSlPiGlHw1pqAZNZjf59U/E74g0o=,tag:JaVmhylGbXurHQoxgb2qGw==,type:str]
    X_API: ENC[AES256_GCM,data:4k318roXyu15uMq1H0sIlysBlRqYAYo9MhCm9W45U3ksScX/nRG9GG/iS06bSEaNkVTZOgFsoA1URw==,iv:Pc29Ns1ii/BAhLaGZZ53HrsO2Q2W0rtnAVv7zL+pvZc=,tag:kdBSP3y393lbBEepnCDIYQ==,type:str]
    X_API_KEY: ENC[AES256_GCM,data:Cz5sLfVsBEaLhCHh3K6/pe4XhsiH1W6GMDYlPoJwVkuksAtjPvtFdu7ToiplDgfqm15TjKtfpCQzGXMlBSZ4Aw==,iv:WXev7N19L+JTDMfcmsPzxzYKgqeLJpLYka9MBbYUR/w=,tag:HU+qUOMUyhLKyyUcODtUZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qqrug292zfrtvwaqypg35mln0chayu5wnwaj66valpz9q4hae9ws9cr8mh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUnFmZVNWL3R6Z09KOFVT
            VVRReE5MbGlyY3RMQ0gwZGY4UFhjMkRKRUEwCm1DOWRCVDZMQkVObmJaZTM3Tnln
            TUdNV0ZaMy9vY3F5MDN5aGJmTUtjOWcKLS0tIGtuS2ZvZzQrdk9OMlcvY2N1OVRj
            UHd5R29vczZjSC9JK3lFeXVqNnY4UGsKhbJq+AS0AgPxkdgWai8pMuKJrWhJMlaq
            zZCbMaST/cL/qnxRPo7Rsv4GxWnQf29o/xJNUjSUGNfFwR1e47bYQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-21T17:27:34Z"
    mac: ENC[AES256_GCM,data:LPMqt1Q+OHCy4l7SF3bsxyd2Vnb05+NqVbwOUWM6SB4Fa70Axy8ZV3bALT4ssyxEsFsWyRBVVzSCM1DbGRroNUwT3mOHyNJD8H075qQNj3Ox3suRveIAINSXtmszYVYg4BKcgnkALNATxQFbLOH7tiVKGsoPrTiT8A0r2pu3QZU=,iv:Dj/AzYWM14SK5lASveE/IbHfbbFInnLcD0fp4662nSg=,tag:Lba8WMQWfnf1Vm6lgfn5bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
