kind: Deployment
apiVersion: apps/v1
metadata:
  name: pelando-api-deployment
  namespace: production-apps
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pelando-api
  template:
    metadata:
      labels:
        app: pelando-api
    spec:
      containers:
        - name: pelando-api
          image: docker.io/rempeloliveira/public:pelando-api.0.0.1
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: pelando-api-secrets
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
